# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
    dead_code: warning

linter:
  rules:
    prefer_final_locals: true
    prefer_final_in_for_each: true
    always_use_package_imports: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_single_quotes: true
    use_build_context_synchronously: false
