name: flutter_social_videos_downloader
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  video_player: ^2.9.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  gal: ^2.3.2
  video_thumbnail: ^0.5.3
  permission_handler: ^12.0.1
  get_it: ^8.2.0
  dio: ^5.5.0+1
  fluttertoast: ^8.2.7
  intl: ^0.20.2
  chewie: ^1.8.3
  adaptive_theme: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
